- name: create ec2 launch config
  hosts: localhost
  connection: local
  vars_files:
     - /home/rajgali83/accesskey
  tasks:
  - name: ec2 lc create
    ec2_lc:
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      name: "{{ launch_config }}"
      image_id: ami-0d6621c01e8c2de2c
      instance_type: t2.micro
      #key_name: ec2admin
      security_groups: ['sg-0598125554496fb8f']
      region: us-west-2
      user_data_path: ./user_data
  
  - name: creating elb
    ec2_elb_lb: 
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      name: "{{ elb_name }}"
      state: present
      region: us-west-2
      cross_az_load_balancing: yes
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
      tags:
        name: shivaelb
      security_group_ids: sg-0598125554496fb8f
      zones: us-west-2a
      health_check:
        ping_protocol: http
        ping_port: 80
        ping_path: "/index.html"
        response_timeout: 5
        interval: 30
        unhealthy_threshold: 2
        healthy_threshold: 2
        
  - name: create auto scaling group
    ec2_asg: 
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      name: "{{ asg_name }}"
      region: us-west-2
      #availability_zones: ['us-west-2a']
      load_balancers: "{{ elb_name }}"
      launch_config_name: "{{ launch_config }}"
      min_size: 1
      max_size: 1
      desired_capacity: 1
      replace_all_instances: yes
      vpc_zone_identifier: ['subnet-098ffa6679adbe82d']
      tags: 
        - type: shiva_web_server
      wait_for_instances: yes
      
  - name: Get elb facts
    ec2_elb_info:
       aws_access_key: "{{ accesskey }}"
       aws_secret_key: "{{ secretkey }}"
       region: us-west-2
       names: "{{ elb_name }}"
    register: elb_info
  - name: create dns record
    route53:
       aws_access_key: "{{ accesskey }}"
       aws_secret_key: "{{ secretkey }}"
       state: present
       zone: sampleappaddress.com
       record: www.sampleappaddress.com
       type: A
       value: "{{ elb_info.elbs.0.dns_name }}"
       alias: True
       alias_hosted_zone_id: "{{ elb_info.elbs.0.hosted_zone_id }}"
       overwrite: yes    
