- name: create ec2 launch config
  hosts: localhost
  connection: local
  vars_files:
     - /home/rajgali83/accesskey
  tasks:
  - name: ec2 lc create
    ec2_lc:
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      name: "{{ launch_config }}"
      image_id: ami-0d6621c01e8c2de2c
      instance_type: t2.micro
      #key_name: ec2admin
      security_groups: ['sg-0598125554496fb8f']
      region: us-west-2
      user_data_path: /home/rajgali83/user_data
  
  - name: creating elb
    ec2_elb_lb: 
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      name: shivawebelb
      state: present
      region: us-west-2
      cross_az_load_balancing: yes
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
      tags:
        name: shivaelb
      security_group_ids: sg-0598125554496fb8f
      zones: us-west-2a
      health_check:
        ping_protocol: http
        ping_port: 80
        ping_path: "/index.html"
        response_timeout: 5
        interval: 30
        unhealthy_threshold: 2
        healthy_threshold: 2
